pool:
  vmImage: "ubuntu-16.04"

stages:
  - template: .azure-pipelines/build.yml
  # - template: .azure-pipelines/deploy-<REPLACE-WITH-STRATEGY>.yml
  #     parameters:
  #       condition: "or(eq(variables['build.sourceBranch'], 'refs/heads/develop'), eq(variables['build.sourceBranch'], 'refs/heads/master'))"
  #       environment: 'Test'
